/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author danil
 */
public class TelaPlaylist extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPlaylist.class.getName());

    /**
     * Creates new form TelaPlaylist
     */
    public TelaPlaylist() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNomePlaylist = new javax.swing.JTextField();
        btEditar = new javax.swing.JButton();
        btCriar = new javax.swing.JButton();
        Btexcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ListaDeFavoritos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btEditar.setText("Editar");
        btEditar.addActionListener(this::btEditarActionPerformed);

        btCriar.setText("Criar");
        btCriar.addActionListener(this::btCriarActionPerformed);

        Btexcluir.setText("Exclói");
        Btexcluir.addActionListener(this::BtexcluirActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "ID", "Nome da playlist"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        ListaDeFavoritos.setText("Ver lista de fvoritos");
        ListaDeFavoritos.addActionListener(this::ListaDeFavoritosActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNomePlaylist)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btCriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(btEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Btexcluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ListaDeFavoritos)))
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtNomePlaylist, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btexcluir)
                    .addComponent(btEditar)
                    .addComponent(btCriar)
                    .addComponent(ListaDeFavoritos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed

        int linha = jTable1.getSelectedRow();
        String novoNome = txtNomePlaylist.getText();
        
        if (linha == -1 || novoNome.equals("")) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma lista na tabela e digite o novo nome na caixa de texto!");
        } else {
            int id = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            
            new dao.PlaylistDAO().editarPlaylist(id, novoNome);
            
            txtNomePlaylist.setText("");
            
            // Atualiza a tabela
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); 
            for(Object[] l : new dao.PlaylistDAO().listarPlaylists()) {
                modelo.addRow(l);
            }
        }
        
    }//GEN-LAST:event_btEditarActionPerformed

    private void btCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCriarActionPerformed

        String nome = txtNomePlaylist.getText();
        
        // Salva no banco
        new dao.PlaylistDAO().criarPlaylist(nome);
        
        // Limpa o campo de texto
        txtNomePlaylist.setText("");
        
        // Atualiza a tabela
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 
        for(Object[] linha : new dao.PlaylistDAO().listarPlaylists()) {
            modelo.addRow(linha);
        }
        
    }//GEN-LAST:event_btCriarActionPerformed

    private void BtexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtexcluirActionPerformed

        int linhaSelecionada = jTable1.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma playlist para excluir!");
        } else {
            int idParaApagar = Integer.parseInt(jTable1.getValueAt(linhaSelecionada, 0).toString());
            
            new dao.PlaylistDAO().excluirPlaylist(idParaApagar);
            
            // Atualiza a tabela
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); 
            for(Object[] l : new dao.PlaylistDAO().listarPlaylists()) {
                modelo.addRow(l);
            }
        }
        
    }//GEN-LAST:event_BtexcluirActionPerformed

    private void ListaDeFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ListaDeFavoritosActionPerformed

        int linha = jTable1.getSelectedRow(); // jTable1 aqui é a tabela de Playlists
        
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione uma playlist na tabela para ver os vídeos dela!");
        } else {
            int idPlaylist = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            String nomePlaylist = jTable1.getValueAt(linha, 1).toString();
            
            // Vamos criar uma mensagem que mostra todos os vídeos encontrados
            String mensagem = "Vídeos na playlist " + nomePlaylist + ":\n\n";
            
            for (Object[] v : new dao.PlaylistDAO().listarVideosDaPlaylist(idPlaylist)) {
                mensagem += "- " + v[1] + " (" + v[3] + ")\n";
            }
            
            javax.swing.JOptionPane.showMessageDialog(this, mensagem);
        }

    }//GEN-LAST:event_ListaDeFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPlaylist().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btexcluir;
    private javax.swing.JButton ListaDeFavoritos;
    private javax.swing.JButton btCriar;
    private javax.swing.JButton btEditar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtNomePlaylist;
    // End of variables declaration//GEN-END:variables
}
