/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author danil
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaPrincipal.class.getName());

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Atualiza = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        Novovideo = new javax.swing.JButton();
        Editar = new javax.swing.JButton();
        txtBusca = new javax.swing.JTextField();
        btBuscar = new javax.swing.JButton();
        Curtir = new javax.swing.JButton();
        Descurtir = new javax.swing.JButton();
        btFavoritos = new javax.swing.JButton();
        BTAddFavoritos = new javax.swing.JButton();
        btExcluirFavoritos = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "titulo", "tipo", "genero", "Situação", "likes", "deslike"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        Atualiza.setText("atualiza");
        Atualiza.addActionListener(this::AtualizaActionPerformed);

        Excluir.setText("Exclói");
        Excluir.addActionListener(this::ExcluirActionPerformed);

        Novovideo.setText("Novo Video");
        Novovideo.addActionListener(this::NovovideoActionPerformed);

        Editar.setText("Editar");
        Editar.addActionListener(this::EditarActionPerformed);

        txtBusca.addActionListener(this::txtBuscaActionPerformed);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(this::btBuscarActionPerformed);

        Curtir.setText("Joinha");
        Curtir.addActionListener(this::CurtirActionPerformed);

        Descurtir.setText("Deslike");
        Descurtir.addActionListener(this::DescurtirActionPerformed);

        btFavoritos.setText("Favoritos");
        btFavoritos.addActionListener(this::btFavoritosActionPerformed);

        BTAddFavoritos.setText("Adicionar aos favoritos");
        BTAddFavoritos.addActionListener(this::BTAddFavoritosActionPerformed);

        btExcluirFavoritos.setText("Remover dos favoritos");
        btExcluirFavoritos.addActionListener(this::btExcluirFavoritosActionPerformed);
        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btBuscar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 46, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Novovideo)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(Excluir)
                                            .addComponent(Editar)
                                            .addComponent(Atualiza)))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Curtir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Descurtir)
                                .addGap(86, 86, 86)
                                .addComponent(btFavoritos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTAddFavoritos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btExcluirFavoritos)))
                        .addGap(78, 78, 78)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBusca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Novovideo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Excluir)
                        .addGap(18, 18, 18)
                        .addComponent(Atualiza, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(288, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Curtir)
                            .addComponent(Descurtir)
                            .addComponent(btFavoritos)
                            .addComponent(btExcluirFavoritos)
                            .addComponent(BTAddFavoritos))
                        .addContainerGap(29, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AtualizaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtualizaActionPerformed

        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        
        modelo.setRowCount(0); 
        
        dao.VideoDAO dao = new dao.VideoDAO();
        
        for(Object[] linha : dao.listarVideos()) {
            modelo.addRow(linha);
        }

    }//GEN-LAST:event_AtualizaActionPerformed

    private void NovovideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovovideoActionPerformed

    TelaCadastro telaNovo = new TelaCadastro();

    telaNovo.setVisible(true);

    telaNovo.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_NovovideoActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed

        int linhaSelecionada = jTable1.getSelectedRow();
        
        if (linhaSelecionada == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Por favor, clique em um vídeo na tabela antes de excluir!");
        } else {
            
            String idTexto = jTable1.getValueAt(linhaSelecionada, 0).toString();
            int idParaApagar = Integer.parseInt(idTexto);
            
            dao.VideoDAO dao = new dao.VideoDAO();
            dao.excluirVideo(idParaApagar);
            
            javax.swing.JOptionPane.showMessageDialog(this, "Vídeo apagado com sucesso! Clique em 'atualiza' para ver a tabela limpa.");
        }

    }//GEN-LAST:event_ExcluirActionPerformed

    private void EditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditarActionPerformed

        int linha = jTable1.getSelectedRow();
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo para editar!");
        } else {
            String id = jTable1.getValueAt(linha, 0).toString();
            String titulo = jTable1.getValueAt(linha, 1).toString();
            String tipo = jTable1.getValueAt(linha, 2).toString();
            String genero = jTable1.getValueAt(linha, 3).toString();
            String situacao = jTable1.getValueAt(linha, 4).toString();

            TelaCadastro tela = new TelaCadastro();
            tela.preencherCampos(id, titulo, tipo, genero, situacao); 
            tela.setVisible(true);
            tela.setLocationRelativeTo(null);
        
        
}    }//GEN-LAST:event_EditarActionPerformed

    private void txtBuscaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscaActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        
        String nomeBusca = txtBusca.getText();
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        modelo.setRowCount(0); 
        
        dao.VideoDAO dao = new dao.VideoDAO();
        
        for(Object[] linha : dao.buscarVideoPorNome(nomeBusca)) {
            modelo.addRow(linha);
        

         }    }//GEN-LAST:event_btBuscarActionPerformed

    private void CurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CurtirActionPerformed
int linha = jTable1.getSelectedRow();
        
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo na tabela para curtir!");
        } else {
            // Pega o ID da linha selecionada
            int id = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            
            // Manda o DAO curtir
            new dao.VideoDAO().curtirVideo(id);
            
            // Atualiza a tabela automaticamente para você ver o número subir na hora
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); 
            for(Object[] l : new dao.VideoDAO().listarVideos()) {
                modelo.addRow(l);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_CurtirActionPerformed

    private void DescurtirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DescurtirActionPerformed
int linha = jTable1.getSelectedRow();
        
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo na tabela para descurtir!");
        } else {
            // Pega o ID da linha selecionada
            int id = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            
            // Manda o DAO descurtir
            new dao.VideoDAO().descurtirVideo(id);
            
            // Atualiza a tabela automaticamente para você ver o número descer na hora
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            modelo.setRowCount(0); 
            for(Object[] l : new dao.VideoDAO().listarVideos()) {
                modelo.addRow(l);
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_DescurtirActionPerformed

    private void btFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFavoritosActionPerformed


        new TelaPlaylist().setVisible(true);
        
    }//GEN-LAST:event_btFavoritosActionPerformed

    private void BTAddFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTAddFavoritosActionPerformed

        int linha = jTable1.getSelectedRow();
        
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo na tabela primeiro!");
        } else {
            // Pega o ID do vídeo que você clicou
            int idVideo = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            
            // Abre uma caixinha pedindo o ID da playlist
            String resposta = javax.swing.JOptionPane.showInputDialog(this, "Digite o ID da sua Playlist (veja na tela de Gerenciar Favoritos):");
            
            if (resposta != null && !resposta.isEmpty()) {
                int idPlaylist = Integer.parseInt(resposta);
                
                // Manda o DAO conectar os dois!
                new dao.PlaylistDAO().adicionarVideo(idPlaylist, idVideo);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Vídeo adicionado à playlist com sucesso!");
            }
        }

    }//GEN-LAST:event_BTAddFavoritosActionPerformed

    private void btExcluirFavoritosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirFavoritosActionPerformed

        int linha = jTable1.getSelectedRow();
        
        if (linha == -1) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um vídeo na tabela primeiro!");
        } else {
            int idVideo = Integer.parseInt(jTable1.getValueAt(linha, 0).toString());
            
            String resposta = javax.swing.JOptionPane.showInputDialog(this, "De qual Playlist você quer remover esse vídeo? (Digite o ID):");
            
            if (resposta != null && !resposta.isEmpty()) {
                int idPlaylist = Integer.parseInt(resposta);
                
                new dao.PlaylistDAO().removerVideo(idPlaylist, idVideo);
                
                javax.swing.JOptionPane.showMessageDialog(this, "Vídeo removido da playlist!");
            }
        }

    }//GEN-LAST:event_btExcluirFavoritosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaPrincipal().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atualiza;
    private javax.swing.JButton BTAddFavoritos;
    private javax.swing.JButton Curtir;
    private javax.swing.JButton Descurtir;
    private javax.swing.JButton Editar;
    private javax.swing.JButton Excluir;
    private javax.swing.JButton Novovideo;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btExcluirFavoritos;
    private javax.swing.JButton btFavoritos;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtBusca;
    // End of variables declaration//GEN-END:variables

}